Adjust columns in "help *" for initial blanks in list. Sync with bashdb.

diff --git a/zshdb.in b/zshdb.in
--- a/zshdb.in
+++ b/zshdb.in
@@ -1,6 +1,6 @@
 #!@SH_PROG@ -f
 # -*- shell-script -*-
-# zshdb - top-level debugger program.
+# Top-level debugger program. This program may be initially invoked.
 #
 #   Copyright (C) 2008, 2009, 2010 Rocky Bernstein <rocky@gnu.org>
 #
@@ -44,7 +44,7 @@ typeset _Dbg_libdir=@PKGDATADIR@
 
 # We agonize a bit over _Dbg_libdir: the root directory for where
 # debugger code is stored. Below is just the first guess...
-[[ ! -d $_Dbg_libdir ]] && _Dbg_libdir='.'
+[[ -d $_Dbg_libdir ]] || _Dbg_libdir='.'
 
 # More _Dbg_libdir finding: respect any library option the user has
 # supplied over any of the above guesses. Go over options and parse
@@ -63,6 +63,14 @@ fi
 unset libdir
 
 # All _Dbg_libdir setting done above. Have we succeeded? 
+if [[ ! -d $_Dbg_libdir ]] ; then 
+  echo "${_Dbg_pname}: Can't read debugger library directory '${_Dbg_libdir}'."
+  echo "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
+  echo "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
+  echo "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
+  exit 1
+fi
+
 typeset _Dbg_main="$_Dbg_libdir/dbg-main.sh"
 if [[ ! -r $_Dbg_main ]] ; then 
   print "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'."
@@ -77,7 +85,7 @@ fi
 
 _Dbg_set_debugger_entry
 
-# Note that this is called via zshdb rather than "zsh --debugger" or zshdb-trace
+# Note that this is called via zshdb rather than zshdb-trace
 _Dbg_script=1
 
 if [[ -n $_Dbg_EXECUTION_STRING ]] ; then
